on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "login to Doker hub"
        run : docker login --username mohamedabdallahrashadahmed5555 --password dckr_pat_P-xoWz6bPfH2d7F9dbGT6axrYCM

      

      
        
      
